language:
  - c

sudo:
  - true

os:
  - linux

addons:
  apt:
    packages:
      - build-essential
      - libglib2.0-dev
      - libncursesw5-dev
      - libmpg123-dev
      - libao-dev
      - libasound2-dev
      - libtagc0-dev
      - libcurl4-openssl-dev
      - libssl-dev
      - help2man

script:
  - ./configure
  - make
  - sudo make install
  - namp --version
